# Generated by Django 3.1.7 on 2021-03-08 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_evento_localidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='localidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
