# Generated by Django 3.1.7 on 2021-03-09 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_evento_localidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='localidade',
        ),
    ]
